### ISSUE TITLE
'edition' in entries

### ISSUE THREAD

**Issue by thwmurph** [iucogs/pubs#10]
I'm not sure whether to label this as a problem or not, but something I've noticed is that, whenever there's an entry that is a specific edition and I put the specific numerical value needed to fulfill the required edition in the 'edition' section and save the entry, it never actually appears in the 'preview' underneath the 'raw' citation afterwards. Maybe it's just because it's a preview citation, but I wasn't sure.

**Comment by pjcraig** [comment]
So edition number should show up for books in any case. I've fixed it and it'll be rolled out to master with the next push.
