### ISSUE TITLE
back/next in edit pane not saving

### ISSUE THREAD

**Issue by JaimieMurdock** [iucogs/pubs#12]
In the pubs interface the Back/Next buttons should, at the very least, ask if you want to save the changes, or auto-save (which would be the expected behavior as you are going through multiple citations.

**Comment by pjcraig** [comment]
gonna go ahead and prompt for manual save while autosaving gets worked out. leaving this one open till then.

**Comment by JaimieMurdock** [comment]
Any progress here?

**Comment by pjcraig** [comment]
Still working on this one, expect to have it done tomorrow.

**Comment by pjcraig** [comment]
update: still working on this. it saves now but the ajax callback is messed up.

Everybody loves Javascript!

**Comment by pjcraig** [comment]
done!
