### ISSUE TITLE
articles "in proceedings" not printing APA format with book title field

### ISSUE THREAD

**Issue by JaimieMurdock** [iucogs/pubs#14]
The book title field is not being published on "in proceedings" citations, which makes them unusable:

Murdock, J., Buckner, C. & Allen, C. (2012). Containing the Semantic Explosion. In A. Monnin, H. Halpin & L. Carr (Eds.) . Lyon, France: CEUR Conference Proceedings.

should be:
Murdock, J., Buckner, C. & Allen, C. (2012). Containing the Semantic Explosion. In Proceedings of the WWW2012 PhiloWeb Workshop. A. Monnin, H. Halpin & L. Carr (Eds.) . Lyon, France: CEUR Conference Proceedings.

**Comment by JaimieMurdock** [comment]
I've fixed this on a private branch, will push tomorrow.

**Comment by pjcraig** [comment]
Did you push this yet, Jaimie?

**Comment by JaimieMurdock** [comment]
Pushed to dev.
