### ISSUE TITLE
unable to open InPhO page

### ISSUE THREAD

**Issue by thwmurph** [iucogs/pubs#38]
I get open any other webpage, but I am unable to connect to InPhO in particular.

**Comment by JaimieMurdock** [comment]
I can access https://inpho.cogs.indiana.edu. What URL are you trying to
access?

**Comment by thwmurph** [comment]
I'm trying to get to where I can view the tickets and add comments to them: I believe this to be the url: http://indphodev.cogs.indiana.edu/

**Comment by pjcraig** [comment]
Would it be [this](http://inphodev.cogs.indiana.edu:8000) ? I think you've got an extra d in there. inphodev.cogs.indiana.edu loads for me. If you're still having issues with it, maybe try clearing your cache.
