### ISSUE TITLE
Sort default error.

### ISSUE THREAD

**Issue by reberle** [iucogs/pubs#4]
Sort should default to sort-by-author.  It is defaulting sort-by-year.

**Comment by pjcraig** [comment]
Collections now sort by the first author by default. Closing this. If I misinterpreted the bug and it's still not working, email me.

**Comment by pjcraig** [comment]
While the sort does work, sometimes it fails to refresh after a new sort has been applied. Interesting! Reopening to look at that.

**Comment by pjcraig** [comment]
Sorts now happen reliably outside of collections. Closing this and opening something more specific to that issue.
