### ISSUE TITLE
unable to fill in certain data

### ISSUE THREAD

**Issue by thwmurph** [iucogs/pubs#5]
i was working in pubs today and everything was going fine, but then there was suddenly no spaces to type in text in certain areas; i am unable to put anything in the author spots, publisher spot, editor spot, journal spot, and possibly some other random things. the actual spots themselves are there, but there's no area to put in text.

**Comment by pjcraig** [comment]
Hey Tom,

Could you give us a screenshot of what's going on? I'm using pubs from home and I'm not really seeing anything like what you're describing.

Thanks, 
Patrick

**Comment by thwmurph** [comment]
I actually just got on and everything seems to be fine now, but I do have a screenshot of when it was a problem. I'm not sure what caused it or if it'll come back, so I'll just send you it for future references.

Tom

**Comment by pjcraig** [comment]
Go ahead and send it to pjcraig@indiana.edu. I'll reopen this issue if it happens again, but for now I'm closing it.
