### ISSUE TITLE
inpho not responding

### ISSUE THREAD

**Issue by thwmurph** [iucogs/pubs#56]
I can't access the InPhO site (inphodev.cogs.indiana.edu) at all.

**Comment by JaimieMurdock** [comment]
What are you trying to get to on inphodev?

**Comment by thwmurph** [comment]
?I was just trying to get to the ticket areas so I can leave comments for the specific collection being analyzed. I just tried again and it appears to be working now so there doesn't seem to be an issue anymore. I continued trying to get it to work at the time though through many different web browsers for quite awhile, so I'm not really sure what happened.
