### ISSUE TITLE
Collections table user_id does not have data

### ISSUE THREAD

**Issue by JaimieMurdock** [iucogs/pubs#6]
The collections table user_id column is all 0s, when it should correspond to the user_id of the user specified in the owner column. After updating the user_id column, the owner column should be dropped, and the PHP code will need to be refactored to grab the owners by id rather than name.

**Comment by pjcraig** [comment]
Abhinav, could you take a look at this? Thanks!

**Comment by agrane** [comment]
I have made the changes for the same will push into dev.
