### ISSUE TITLE
Sorting in collections behaving... NOT!

### ISSUE THREAD

**Issue by pjcraig** [iucogs/pubs#8]
Sorting all citations by the options we currently have available seems to work fine. But for some reason when you enter a collection, it defaults to sorting by whatever is set as the sort order at the top of Page.js. 

Currently that's citation_id but it can be changed to any one of the four search options we've currently got.

Places for us to start looking: Collections.js

**Comment by pjcraig** [comment]
Hey Ruth, any progress on this one?

**Comment by reberle** [comment]
No, but it's high on my to-do list.

**Comment by reberle** [comment]
Added `$sort_order` to parameter list in `getCitationsGivenCollectionID` in citations.php.
