### ISSUE TITLE
"Date Retrieved" for Web Published entries

### ISSUE THREAD

**Issue by thwmurph** [iucogs/pubs#9]
a problem I've noticed quite often is when a web published entry needs the "date retrieved" box filled in, but when I put in the date and save the entry, it always takes out the last numerical value. for example, if I put "May 8, 2009" it will only receive "May 8, 200"

**Comment by pjcraig** [comment]
I'll be taking a look at this at some point today.

**Comment by pjcraig** [comment]
Found the issue: the field for date_retrieved in the database was too small. It's now been fixed.
